version: "3.8"
services:
  proxy:
    image: proxy
    build:
      args:
        uid: 1000
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./config:/etc/nginx/conf.d
      - ./sites-available:/etc/nginx/sites-available
      - ./sites-enabled:/etc/nginx/sites-enabled
    networks:
      - reverse-proxy

networks:
  reverse-proxy:
    external: true
