version: "3.8"
services:
  proxy:
    image: proxy
    build:
      args:
        uid: 1000
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
    networks:
      - reverse-proxy

networks:
  reverse-proxy:
    external: true
